name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: change-string-case
        uses: ASzc/change-string-case-action@v1
        with:
          string: {{ github.repository }}
          case: lowercase

      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/{{ steps.change-string-case.outputs.lowercase }}:${{ inputs.version }}